#!/bin/bash

## Usage:

function help {
    echo "Usage: scriptname -i:o:s:p:m:
     	-i with argument = input file path
	-m min peak length
"
}


if [ $# -eq 0 ]
then help
exit
fi

while getopts "i:o:s:p:m:" arg; do
    case $arg in
        i) IN=$OPTARG;;
	m) MIN=$OPTARG;;
	*) help;;
    esac
done

awk -v "MIN=$MIN" '{if ($3-$2 >= MIN) print $0}' $IN
